id: atmLambdaConfigBadValue
args:
  - name: parameterName
    type: Binary
  - name: specificError
    type: OnedataError
description: >-
  Bad value provided for parameter "{parameterName}" of lambda config: {specificError}
http_code: 400
