id: atmLambdaConfigBadValue
description: "Bad value provided for parameter \"{parameterName}\" of lambda config (see details)."
http_code: 400
args:
  - name: parameterName
  - name: specificError
    type: error
